name: Build

on:
  push:
    branches: [ "feature/**" ]
  pull_request:
    branches: [ "feature/**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # チェックアウト
    - uses: actions/checkout@v3
    
    # JDKのセットアップ
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    # Gradleのキャッシュ復元
    - uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys:
          ${{ runner.os }}-gradle-
          
    # 依存関係の出力
    - name: Displays the Android dependencies of the project
      run: ./gradlew androidDependencies

    # コンパイル
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleDebug
