name: Lint

on:
  pull_request:
    branches:
      - feature/**

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    # チェックアウト
    - uses: actions/checkout@v2
    
    # 静的解析
    - uses: Run Inspection
      run: ./gradlew lint
      
    # 結果の表示
    - name: Show Results on GitHub
      uses: yutailang0119/action-android-lint@v1
      with:
        xml_path: '**/build/reports/lint-results-*.xml'
        
    # アーティファクトアップロード
    - name: Upload results Artifact
      uses: actions/upload-artifact@v2
      if: success() || failure()
      with:
        name: results
        path: |
          **/build/reports/lint-results-*.html
          **/build/reports/lint-results-*.xml
        if-no-files-found: error
        retention-days: 14
